### ISSUE TITLE
URL format at myepisode.com

### ISSUE THREAD

**Issue by ipottinger** [maximeh/script.myepisodes#13]
It seems that there are a few changes happening at myepisodes.com, including some URL format alterations that I suspect are now causing (my) installs of this add-on to fail. Everything was working fine till sometime during the past 24 hrs.

In a recent post (http://www.myepisodes.com/forum/viewtopic.php?p=9047#9047), myepisode.com founder "IceMan" makes mention of new "Pritty URLs". 

I see the following error in Kodi's log file:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : 
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.KeyError'>
Error Contents: ('showid',)
Traceback (most recent call last):
	File "C:\Users\ipott\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 185, in <module>
		player = Player()
	File "C:\Users\ipott\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 36, in __init__
		self.mye = self._loginMyEpisodes()
	File "C:\Users\ipott\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 93, in _loginMyEpisodes
		if mye.is_logged and (not mye.get_show_list()):
	File "C:\Users\ipott\AppData\Roaming\Kodi\addons\script.myepisodes\resources\lib\myepisodes.py", line 82, in get_show_list
		showid = urlparse.parse_qs(link_url)['showid'][0]
KeyError: ('showid',)
-->End of Python script error report<--
```

From the traceback, __it looks like the last call to urlparse.parse_qs(link_url)['showid'][0] fails because 'showid' does not appear in the URLs.__ I did not take note of the format of the URLs before now so I can't be certain that this is the reason, but it is my best guess. I filed a bug report on myepisode.com at http://www.myepisodes.com/forum/viewtopic.php?t=2917.

Thanks for the fantastic add-on. I greatly appreciate the time and effort you've chosen to graciously share.

**Comment by maximeh** [comment]
Hi Ian,

Thanks a lot for reporting this issue (and thank you for the quality of the issue, it's very clear and precise).

I think you are right and the change in the URL format broke the way the add-on communicate with MyEpisodes (lack of API).
I will fix that a soon as I can, I don't think I'll be able to do it tonight, but tomorrow should be good.

I'll keep you posted.

**Comment by ipottinger** [comment]
Thanks Maxime,

IceMan passed along some notes in the bug report on myepisode.com. I hope it is useful. Check them out at http://www.myepisodes.com/forum/viewtopic.php?t=2917.

**Comment by maximeh** [comment]
Hi Ian,

I pushed some commits, would you be so kind as to test it ? If you need help to create a plugin from the source, please ask.

**Comment by YoYoost** [comment]
It gives this error 
``
:29:35 148845.109375 T:1539306416  NOTICE: -->Python Interpreter Initialized<--
15:29:40 148850.500000 T:1530917808  NOTICE: Previous line repeats 2 times.15:29:40 148850.500000 T:1530917808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "/home/xbian/.kodi/addons/script.myepisodes/default.py", line 200, in <module>
                                                player = Player()
                                              File "/home/xbian/.kodi/addons/script.myepisodes/default.py", line 35, in __init__
                                                self.mye = self._loginMyEpisodes()
                                              File "/home/xbian/.kodi/addons/script.myepisodes/default.py", line 92, in _loginMyEpisodes
                                                if mye.is_logged and (not mye.get_show_list()):
                                              File "/home/xbian/.kodi/addons/script.myepisodes/resources/lib/myepisodes.py", line 82, in get_show_list                                                showid = link.split('/')[2]                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--

**Comment by maximeh** [comment]
Thanks a lot @YoYoost, I'll do some proper testing/debugging tonight. I did not had time yesterday. I'll inform you guys when it's working.

**Comment by ipottinger** [comment]
Sorry Maxime for not getting back to you earlier. I've been busy. 

I'm assuming I can just drop the contents of the repository into the appropriate folder in Kodi? If not, let me know exactly what to do. Thanks again.

**Comment by maximeh** [comment]
@ipottinger @YoYoost Hi guys, I have made a pre-release with a version 1.2.1 so it's easier for you to test.

I have tested on my side and have no problem so far, if you have any issues please report. If it works for you too, so I can close this issues and ask the Kodi addon maintainer to bump the addon version.

**Comment by YoYoost** [comment]
@ipottinger fwiw there is an instruction how to build a addon (https://github.com/maximeh/script.myepisodes).

@maximeh I just installed the addon you built and it logged in fine. I am now checking if a episode will trigger the mark watched correctly. I will report back.

**Comment by ipottinger** [comment]
Thanks @YoYoost and @maximeh

Dropping the contents of the repository into the appropriate folder in Kodi worked fine for me. The add-on is now marking episodes as watched again. As far as I can tell, it is working fine now.

**Comment by maximeh** [comment]
@YoYoost @ipottinger Thanks to both of you. I'm closing this issues and releasing this new version for everyone.
