### ISSUE TITLE
Not synchronising with myepisodes.com

### ISSUE THREAD

**Issue by glymph** [maximeh/script.myepisodes#16]
Perhaps the website has changed since the last release, but when I run myepisodes 1.2.8 in Kodi 17.3 under Mac OS, or myepisodes 1.2.6 in Kodi 15.2 on Android (Amazon Firestick), neither version successfully creates shows nor marks episodes as being watched when they should.

There's a pop-up message saying the show was not found when watching a new episode.

**Comment by maximeh** [comment]
Hey there,

Thanks a lot for filling this issue.
I will have a look, hopefully during the week or this week end.

**Comment by maximeh** [comment]
@glymph could do a run with the debug activated ? 
I have ran my unit test (which are not commited yet, I am working on some improvement) and they don't seem to fail. I'd like to get to the bottom of this but need more info.

Thanks a lot !

**Comment by maximeh** [comment]
@glymph hey

I know it's been a while but just so you know; I finished a new version of the addon this week end; I will publish it soon; just need a little bit more testing. Hopefully tonight.

If you are interested; I am always interested by the feedback from some beta testers :)

**Comment by maximeh** [comment]
I have pushed a new version; will update the Kodi addons repository; so I am closing this for now, if you have any other issue, please let me know.
