### ISSUE TITLE
Not compatible with Kodi 19

### ISSUE THREAD

**Issue by oevesque** [maximeh/script.myepisodes#17]
Kodi 19 now use only Python 3. Maybe it's the source of the problem

**Comment by maximeh** [comment]
Oh that's a good point. I need to check that! Thanks for the issue.

**Comment by maximeh** [comment]
I've made necessary changes and it's ongoing over there: https://github.com/xbmc/repo-scripts/pull/1890 
Hopefully it should be accepted soon and you'll get the update through Kodi as usual!

Thanks again for you report!
