### ISSUE TITLE
Not changing watched status.

### ISSUE THREAD

**Issue by Laurvin** [maximeh/script.myepisodes#22]
I installed the addon yesterday and it works partly; it does add shows to my account but it does not change the 'watched' status of any shows after I have watched them. Either new ones just added to the account or ones recognized and already there.

**Comment by maximeh** [comment]
Hi!
Thanks for your report!

Do you have any debug log from XBMC by any chance? That would help quite a lot figure out what's wrong there.

**Comment by Laurvin** [comment]
Here you go!

https://hastebin.com/share/ujepeloqer.yaml

**Comment by maximeh** [comment]
Thanks! I’ll be one more time annoying, could you try seeking towards the very end of your video and then stop playback to trigger the “mark as played” action?

**Comment by Laurvin** [comment]
So not do a seek action till the very end when it stops the video automatically but one to where it is a minute or so from the end and then just stop the video and press escape?

**Comment by Laurvin** [comment]
Hah, I found the issue, it seems. And the issue is me!

When I watch something I never use the stop button at the end. I just let the video run its course so it ends itself or do a seek action so it reaches the end. Either way makes Kodi end the video and return to the list.

And it seems when you do it that way, it doesn't trigger the add-on. I just tried your way and used the actual stop button and it immediately showed that it was marking the episode as watched. I checked on the site, and it did.

So... would it possible to also get the add-on to trigger when the video reaches the end? Thanks!

**Comment by maximeh** [comment]
I probably haven't tried that in a very long time, I'll give it a go and see what happens.

**Comment by Laurvin** [comment]
Thanks!!

**Comment by Laurvin** [comment]
I'm happy to test it for you but how do I install that version?

**Comment by maximeh** [comment]
Lemme build a zip for you.

**Comment by maximeh** [comment]
[script.myepisodes-3.1.0.zip](https://github.com/maximeh/script.myepisodes/files/11131246/script.myepisodes-3.1.0.zip)

Try with that and see if that works better for you, if not; please attach a debug log with the whole sequence (opening; eventually seeking to the last part and then letting it reach its normal end)

**Comment by Laurvin** [comment]
Works perfectly!

I tried both by letting the video run its course by itself and by using seek to go to end manually. In both cases it changed the viewed status. (I did only test with two episodes of one show but I doubt that matters.)

Thank you so much!

**Comment by maximeh** [comment]
Ok I’ll push that to kodi then, thanks for testing!
