### ISSUE TITLE
MyEpisodes picking up all videos played

### ISSUE THREAD

**Issue by newphreak** [maximeh/script.myepisodes#9]
Can you make this filter to only respond to tv-shows? Now when watching movies, or even videos under files, it scobbles the names, and tries to add it as a serie. Which is not good at all.
Edit, if you need logs I can provide it, but this should be simple enough to recreate.

**Comment by maximeh** [comment]
Hi,

I know about this issues, unfortunately, it's very tricky. I personally, don't use XBMC-Kodi's database system, so I only have flat files.
And I assume I'm not the only one to use it that way. Which means that there's no easy way to differentiate a film from a TV Show.

What could be added easily, is a preferences, where the users could say, if a path to a file contains 'movie' it's excluded and we don't touch it.
Also, I could check if XBMC's left some tags and if it's anything but a TV Shows I don't touch it. If there's no info, I have to try since I don't really know.

With both theses settings, I think it could be done. I don't know when I'll have time to implement and test that since I'm very very busy at work at the moment, but I'll sure keep this open.

If you want to tackle it yourself, you are more than welcome :).

**Comment by newphreak** [comment]
Well I don't know how to code. An exclude filter would be highly needed/wanted.
And there are many ways to use kodi, but a simple thing like this shouldn't need to get too complex. So exclude should be all we need for now.

**Comment by maximeh** [comment]
It may go quick or not. I really can't give you an ETA.

Again, thanks for reporting this.

**Comment by maximeh** [comment]
Rah sorry. Did not wanted to close this....

Anyway, it's not a problem, I'll try to find some time to do it, I can't tell when it'll be done though. I'll try to kick myself to do it, otherwise it'll still be open next year :/.
Anyway, thanks again for reporting this.

**Comment by maximeh** [comment]
Hi,

Sorry for the time it took, I just pushed some changes to implement an exclude option, could you care to try and report if this was enough for you ?

**Comment by maximeh** [comment]
Im am closing this issues as it was not updated. I assume the new feature was enough ?

**Comment by castorfou** [comment]
I am just testing this exclude feature and it doesn't work here.
When playing a movie in the exclude path, I have still a myepisode popup saying not found.

**Comment by maximeh** [comment]
Thanks a lot for this report.

I'll test again and see what's wrong with this.

**Comment by maximeh** [comment]
By the way, if you have some logs, it would be great.

**Comment by maximeh** [comment]
@castorfou I've added a new version 1.2.5 which adds also something for the excluded path in case there's non ASCII char in them. Maybe that was your issue, if you could give it a spin and report, it would be great !

Thanks

**Comment by castorfou** [comment]
Thanks a lot. Will try tonight. Not related to i18n I Think.

Any way to add trace ?
Le 26 oct. 2015 11:55 AM, "Maxime Hadjinlian" <notifications@github.com> a
écrit :

**Comment by maximeh** [comment]
Yeah, in [...]resources/lib/myepisodes.py

Find: (Should be line 195
```python
        excludepath = xbmc.translatePath(exclude).decode('utf-8')               
```

And add, after that line:
```python
        print "XXXXXXXXXXX %s: %s" % (setting_name, excludedpath)               
        print "XXXXXXXXXXX filename: %s" % filename 
```

Make sure you respect the indentation otherwise it won't work.
This should help with what's wrong.

I'll need to do a pass on the add-ons to have some unit testing and some more debugging information.

**Comment by castorfou** [comment]
Hi Maximeh,

I have such a line in default.py and not in myepisodes.py.

I have added the log lines.
And I have the following error when playing a movie in the exclude path :+1: 
21:11:48 T:140170074515200   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ZeroDivisionError'>
                                            Error Contents: float division by zero
                                            Traceback (most recent call last):
                                              File "/home/guillaume/.kodi/addons/script.myepisodes-master/default.py", line 157, in onPlayBackStopped
                                                self.onPlayBackEnded()
                                              File "/home/guillaume/.kodi/addons/script.myepisodes-master/default.py", line 162, in onPlayBackEnded
                                                actual_percent = (self._last_pos/self._total_time)*100
                                            ZeroDivisionError: float division by zero
                                            -->End of Python script error report<--

Actually it seems it runs into an error before entering the log lines.

**Comment by maximeh** [comment]
That's really weird, this errors means that when we asked Kodi for the
total duration of the video, it answered 0 (the variable is initialised to
a high value to avoid that).

Could you tell me by what means you were watching (hard drive, nfs, samba,
http, upnp, ...), and if possible share the file/url ?

**Comment by castorfou** [comment]
Sorry Maximeh,
that error happened only once.
I have updated my report : I have modified default.py and not myepisodes.py.
And I don't see anything in logs.

**Comment by maximeh** [comment]
Okey, so the first issues must have been with Kodi.
Yes, it's in default.py, my bad.

If there's some log, it would be when you start to play the file (we don't need to do anything if it's excluded so we do it at the earliest).
You don't even see the log ""_is_excluded(): Check if '%s' is a URL" ? Where '%s' would be a path/URL.

**Comment by maximeh** [comment]
@castorfou I found a really silly bug. This should fix your issue hopefully. Try the latests pre-release.

**Comment by castorfou** [comment]
@maximeh works now !
great, ty very much

**Comment by maximeh** [comment]
Great, I have marked it as an official release and I'll get a hold of the Kodi maintainer.
Thanks for your report and testing !
